# Version 0.3.5
# global configuration
global:
  machine: 'mela' # 'mela' # 'raven'
  evaluate_after: 0

# job configuration important for training
job:
  nodes: 1
  ntasks: 1
  mem-per-task: 300
  cpus-per-task: 1
  time: '24:00:00'
  agent_buffer: 0
  recurrent:
    enable: 0
    n_jobs: 3

# Reinforcement learning configuration
learning:
  # Model options 
  model:
    name: 'PPO' #'RecurrentPPO' 'PPO' 'QRDQN' 'DQN' 'A2C' 'ACKTR' 'ACER' 'DDPG' 'PPO2' 'SAC' 'TRPO'
    policy: 'MlpPolicy' #'MlpLstmPolicy' # 'MlpPolicy'# 'CnnPolicy' # 'MultiInputPolicy'
    model_kwargs:
      n_steps: 1024
      batch_size: 64
      n_epochs: 5
      verbose: 1
      ent_coef: 0.2
      clip_range: 0.001
      learning_rate: 2.e-4
      policy_kwargs:
#        features_extractor_kwargs:
#          cnn_output_dim: 16
        net_arch:
          pi: [256, 256]
          vf: [256, 256]
    total_timesteps: 1.e+7
    save_freq: 1.e+6 # 1.e+6 use string for best reward save, int for every n steps
    model_save_prefix: '21022024_mela_try_reproduce_and_beat_1'
    load:
      enable_loading: 0
      last_model: 0
      saved_model_name: './Training/SavedModels/15022024_3D_LV_mela_train_load_enabled_best_reward'

# Environment configuration
env:
  # general env settings
  type: 'LvEnv' # 'PcEnv' # 'LvEnv' # 'GridEnv' # 'SLvEnv'
  n_envs: 1
  wrap: False
  wrapper: 'VecFrameStack' # 'DummyVecEnv' # 'VecFrameStack' # 'SubprocVecEnv'
  wrapper_kwargs: #
    n_stack: 4
    channels_order: 'last' # use first for image learning and last for number

  # general simulation settings
  observation_type: 'number' # 'image' # 'number' # 'multiobs' # 'mutant_position'
  action_type: 'discrete' # 'discrete' # 'continuous'
  see_resistance: False
  max_tumor_size: 150 #61828 #100000 # 110000 # 4000
  max_time: 150 # 120
  initial_wt: 99.99782 #41219 #2761 # 74291 # 2761
  initial_mut: 0.00218 #8
  growth_rate_wt: 0.078 #0.074 # 0.29 # 0.0175
  growth_rate_mut: 0.213 #0.205 # 0.438 # 0.0175
  death_rate_wt: 0.01 #0.0029
  death_rate_mut: 0.01 #0.00438
  treat_death_rate_wt: 17.998 #3.156 # 0.36 # 0.397 # 0.015
  treat_death_rate_mut: 0.00 # 0.0
  treatment_time_step: 1
  reward_shaping: 0 # reward shaping flag for some predefined rewards
  normalize: True
  normalize_to: 1000.0
  image_size: 124 #84 #124
  patient_sampling:
    enable: 0
    type: 'sequential' # 'random' # 'sequential'
    patient_id: 80 # [1, 4, 55, 80, 93]

  # LV environment settings
  LvEnv:
    carrying_capacity: 463 #244000 # 6500
    competition_wt: 1.433 #2.297 # 1.323 #2400.0
    competition_mut: 1.119 #4.967 # 0.0 #0.336
    growth_function_flag: 'instant' # 'instant', 'delayed', 'delayed_with_noise'
    image_sampling_type: 'dense' #'mutant_position' # 'dense' # 'random'

  SLvEnv:
    carrying_capacity: 244000
    competition_wt: 2.297 #2400.0
    competition_mut: 4.967 #0.336
    growth_function_flag: 'instant' # 'instant', 'delayed', 'delayed_with_noise'
    image_sampling_type: 'mutant_position' #'mutant_position' # 'dense' # 'random'
    mutant_distance_to_front: 150
    cell_volume: 2144
    growth_layer: 150
  # note this is not yet functional
  PcEnv:
    domain_size: 2050 #1250
    cpus_per_sim: 10
    transport_type: 'ipc://' # Linux: 'ipc://' # Windows: 'tcp://'
    transport_address: '/tmp/' # for raven use '/ptmp/saif/', for mela use '/tmp/'. For windows use '5555'
    xml:
      use_2D:
          parent_nodes: ['domain']
          value: 'true'
      number_of_susceptible_cells:
          parent_nodes: ['user_parameters']
          value: 2500
      number_of_resistant_cells:
          parent_nodes: ['user_parameters']
          value: 5
      enable_chkpt:
          parent_nodes: ['user_parameters']
          value: 'true'
      filename_chkpt:
          parent_nodes: ['user_parameters']
          value:  './../paper_presims/patient_80/final' #'./../3D_presim/output/output00000112' # './../paper_presims/patient_80/final'
      treatment_time_step:
          parent_nodes: ['user_parameters']
          value: 720
      treatment_strength:
          parent_nodes: ['user_parameters']
          value: 30.0e2 # 3.0e2 or 6.0e2

  # LatticeBased environment settings
  GridEnv:
    cell_positioning: 'surround_mutant' # 'surround_mutant' # 'random' # 'load'

# evaluation configuration
eval:
  most_recent: 0
  from_file: 1
  path: './data/raven_run_logs/cont_22_run_4'
  model_prefix: '19022024_run_22_load_4'
  step_to_load: '_best_reward'
  save_name: 'cont_4_rav'
  # evaluation settings
  fixed_AT_protocol: 0
  at_type: 'zhang_et_al' # 'mtd' # 'fixed' # 'zhang_et_al'# 'no_treatment'
  threshold: 1.0
  num_episodes: 100
  evaluate_on: 'same' # 'PcEnv' # 'LvEnv' # 'GridEnv'
  pcdl: False