# Version 0.3.5
# global configuration
global:
  machine: 'mela' # 'mela' # 'raven'
  evaluate_after: 0

# job configuration important for training
job:
  nodes: 1
  ntasks: 1
  mem-per-task: 2000
  cpus-per-task: 2
  time: '24:00:00'
  agent_buffer: 0
  recurrent:
    enable: 0
    n_jobs: 2

# Reinforcement learning configuration
learning:
  # Model options 
  model:
    name: 'PPO' #'RecurrentPPO' 'PPO' 'QRDQN' 'DQN' 'A2C' 'ACKTR' 'ACER' 'DDPG' 'PPO2' 'SAC' 'TRPO'
    policy: 'MlpPolicy' #'MlpLstmPolicy' # 'MlpPolicy'# 'CnnPolicy' # 'MultiInputPolicy'
    average_steps: 8
    model_kwargs:
      n_steps: 64
      batch_size: 64
      n_epochs: 5
      verbose: 0
      ent_coef: 1.e-5
      clip_range: 0.05
      learning_rate: 1.e-4
      policy_kwargs:
#        features_extractor_kwargs:
#          cnn_output_dim: 16
        net_arch:
          pi: [ 64, 64 ]
          vf: [ 64, 64 ]
    total_timesteps: 5.e+5
    save_freq: 'best' # 1.e+6 use string for best reward save, int for every n steps
    model_save_prefix: '20240927_3'
    load:
      enable_loading: 0
      last_model: 0
      saved_model_name: './Training/SavedModels/20240826_elv_tendayaverage_test8_best_reward'

# Environment configuration
env:
  # general env settings
  type: 'ArrEnv' # 'PcEnv' # 'LvEnv' # 'GridEnv' # 'SLvEnv' # 'MeltdEnv'
  n_envs: 1
  wrap: False
  wrapper: 'VecFrameStack' # 'DummyVecEnv' # 'VecFrameStack' # 'SubprocVecEnv'
  wrapper_kwargs: #
    n_stack: 4
    channels_order: 'last' # use first for image learning and last for number

  # general simulation settings
  observation_type: 'number' # 'image' # 'number' # 'multiobs' # 'mutant_position'
  action_type: 'discrete' # 'discrete' # 'continuous'
  see_resistance: False
  max_tumor_size: 3.0 # 2006 #3086 #100000 # 110000 # 4000
  max_time: 82 #122 # 120
  initial_wt: 7000 # 1539 #2761 # 74291 # 2761 # 8000 - used for meltd atserhii train
  initial_mut: 8 # 4 # 'random' - used for meltd atserhii train
  growth_rate_wt: 0.12 #0.096 #'0.096pm0.001 ' # 0.079 - meltd. 0.116 - current
  growth_rate_mut: 0.15 #0.12 # 0.076 - meltd. 0.23 - current
  death_rate_wt: 0.1
  death_rate_mut: 0.1
  treat_death_rate_wt: 0.1 #2.076 #'2.076pm0.005' # 2.388 - meltd. 2.57 - current
  treat_death_rate_mut: 0.00 # 0.0
  treatment_time_step: 4
  reward_shaping: 'tendayaverage' # reward shaping flag for some predefined rewards
  normalize: False
  normalize_to: 1000.0
  image_size: 124 #84 #124
  patient_sampling:
    enable: 0
    type: 'sequential' # 'random' # 'sequential'
    patient_id: [ 113 ] # [1, 4, 55, 80, 93]

  # LV environment settings
  LvEnv:
    carrying_capacity: 48300 # '48300pm1210'
    competition_wt: 1.0 # 1.732 - fixed treat #1.772 #1.802 - 1.3# 1.795 # 1.323 #2400.0
    competition_mut: 1.0 # 3.408 #3.299 - 1.3 # 3.319 # 0.0 #0.336
    growth_function_flag: 'instant' #'instant_fixed_treat_with_noise' # 'instant', 'delayed', 'delayed_with_noise'
    image_sampling_type: 'dense' #'mutant_position' # 'dense' # 'random'

  SLvEnv:
    carrying_capacity: 3906
    competition_wt: 1.733 #1.772 #2400.0
    competition_mut: 1.0 #0.336
    growth_function_flag: 'instant_with_noise' # 'instant', 'delayed', 'delayed_with_noise'
    image_sampling_type: 'mutant_position' #'mutant_position' # 'dense' # 'random'
    mutant_distance_to_front: 73.5 #70.5 # 92
    cell_volume: 2144
    growth_layer: 150 # 110
    dimension: 2
    growth_fit: 'quadratic'
  # note this is not yet functional
  PcEnv:
    domain_size: 2050 #1250
    cpus_per_sim: 10
    transport_type: 'ipc://' # Linux: 'ipc://' # Windows: 'tcp://'
    transport_address: '/tmp/' # for raven use '/ptmp/saif/', for mela use '/tmp/'. For windows use '5555'
    xml:
      use_2D:
          parent_nodes: ['domain']
          value: 'true'
      number_of_susceptible_cells:
          parent_nodes: ['user_parameters']
          value: 2500
      number_of_resistant_cells:
          parent_nodes: ['user_parameters']
          value: 5
      enable_chkpt:
          parent_nodes: ['user_parameters']
          value: 'false'
      filename_chkpt:
          parent_nodes: ['user_parameters']
          value:  './../paper_presims/patient_285/final' #'./../3D_presim/output/output00000112' # './../paper_presims/patient_80/final'
      treatment_time_step:
          parent_nodes: ['user_parameters']
          value: 720
      treatment_strength:
          parent_nodes: ['user_parameters']
          value: 6.0e2 # 3.0e2 or 6.0e2

  # LatticeBased environment settings
  GridEnv:
    cell_positioning: 'surround_mutant' # 'surround_mutant' # 'random' # 'load'

  MeltdEnv:
    growth_function_flag: 'delayed_with_noise' # 'instant', 'delayed', 'delayed_with_noise'
    image_sampling_type: 'mutant_position' #'mutant_position' # 'dense' # 'random'
    mutant_distance_to_front: 705.7 #150
    cell_area: 976
    growth_layer: 150
    dimension: 2

  ArrEnv:
    carrying_capacity: 48000
    arrest_rate: 0.7
    recover_rate: 0.1
    arresting_time_threshold: 2
    recovering_time_threshold: 4
    dying_time_threshold: 2
    initial_growth_reduction: 0.5
# evaluation configuration
eval:
  most_recent: 0
  from_file: 0
  path: './'
  model_prefix: '20240927_3'
  step_to_load: '_best_reward'
  save_name: '25_pulse_arrest'
  # evaluation settings
  fixed_AT_protocol: 1
  at_type: 'pulse' # 'mtd' # 'fixed' # 'zhang_et_al'# 'no_treatment'
  threshold: 1.00
  num_episodes: 1
  evaluate_on: 'ArrEnv' # 'PcEnv' # 'LvEnv' # 'GridEnv'
  pcdl: False
