# Version 0.3.1
# global configuration
global:
  machine: 'mela' # 'mela' # 'raven'
  evaluate_after: 0

# job configuration important for training
job:
  nodes: 1
  ntasks: 1
  mem-per-task: 300
  cpus-per-task: 1
  time: '24:00:00'
  agent_buffer: 0
  recurrent:
    enable: 0
    n_jobs: 3

# Reinforcement learning configuration
learning:
  # Model options 
  model:
    name: 'PPO' #'RecurrentPPO' 'PPO' 'QRDQN' 'DQN' 'A2C' 'ACKTR' 'ACER' 'DDPG' 'PPO2' 'SAC' 'TRPO'
    policy: 'MlpPolicy' #'MlpLstmPolicy' # 'MlpPolicy'# 'CnnPolicy' # 'MultiInputPolicy'
    model_kwargs:
      n_steps: 1024
      batch_size: 128
      n_epochs: 10
      verbose: 1
      ent_coef: 0.00001
      clip_range: 0.01
      learning_rate: 5.e-5
      policy_kwargs:
#        features_extractor_kwargs:
#          cnn_output_dim: 16
        net_arch:
          pi: [128, 128]
          vf: [128, 128]
    total_timesteps: 1.e+8
    save_freq: 'best' # 1.e+6 use string for best reward save, int for every n steps
    model_save_prefix: '04032204_mela_vfs_higher_clip'
    load:
      enable_loading: 0
      last_model: 0
      saved_model_name: './Training/SavedModels/29022024_mela_2d_newest_best_reward'

# Environment configuration
env:
  # general env settings
  type: 'PcEnv' # 'PcEnv' # 'LvEnv' # 'GridEnv' # 'SLvEnv'
  n_envs: 1
  wrap: False
  wrapper: 'VecFrameStack' # 'DummyVecEnv' # 'VecFrameStack' # 'SubprocVecEnv'
  wrapper_kwargs: #
    n_stack: 4
    channels_order: 'last' # use first for image learning and last for number

  # general simulation settings
  observation_type: 'mutant_position' # 'image' # 'number' # 'multiobs' # 'mutant_position'
  action_type: 'discrete' # 'discrete' # 'continuous'
  see_resistance: False
  max_tumor_size: 2053 # 2006 #3086 #100000 # 110000 # 4000
  max_time: 250 # 120
  initial_wt: 1539 #2761 # 74291 # 2761
  initial_mut: 4
  growth_rate_wt: 0.087 #0.085 - 1.3# 0.083 # 0.29 # 0.0175
  growth_rate_mut: 0.216 #0.219 - 1.3# 0.223 # 0.438 # 0.0175
  death_rate_wt: 0.01 #0.0029
  death_rate_mut: 0.01 #0.00438
  treat_death_rate_wt: 5.837 #5.986 - 1.3 # 6.07 # 0.36 # 0.397 # 0.015
  treat_death_rate_mut: 0.00 # 0.0
  treatment_time_step: 1
  reward_shaping: 0 # reward shaping flag for some predefined rewards
  normalize: True
  normalize_to: 1000.0
  image_size: 124 #84 #124
  patient_sampling:
    enable: 0
    type: 'sequential' # 'random' # 'sequential'
    patient_id: 80 # [1, 4, 55, 80, 93]

  # LV environment settings
  LvEnv:
    carrying_capacity: 3906 # 6500
    competition_wt: 1.772 #1.802 - 1.3# 1.795 # 1.323 #2400.0
    competition_mut: 3.408 #3.299 - 1.3 # 3.319 # 0.0 #0.336
    growth_function_flag: 'instant' # 'instant', 'delayed', 'delayed_with_noise'
    image_sampling_type: 'dense' #'mutant_position' # 'dense' # 'random'

  SLvEnv:
    carrying_capacity: 3906
    competition_wt: 1.772 #2400.0
    competition_mut: 3.408 #0.336
    growth_function_flag: 'instant' # 'instant', 'delayed', 'delayed_with_noise'
    image_sampling_type: 'mutant_position' #'mutant_position' # 'dense' # 'random'
    mutant_distance_to_front: 120
    cell_volume: 2144
    growth_layer: 150
    dimension: 2
  # note this is not yet functional
  PcEnv:
    domain_size: 2050 #1250
    cpus_per_sim: 10
    transport_type: 'ipc://' # Linux: 'ipc://' # Windows: 'tcp://'
    transport_address: '/tmp/' # for raven use '/ptmp/saif/', for mela use '/tmp/'. For windows use '5555'
    xml:
      use_2D:
          parent_nodes: ['domain']
          value: 'true'
      number_of_susceptible_cells:
          parent_nodes: ['user_parameters']
          value: 2500
      number_of_resistant_cells:
          parent_nodes: ['user_parameters']
          value: 5
      enable_chkpt:
          parent_nodes: ['user_parameters']
          value: 'true'
      filename_chkpt:
          parent_nodes: ['user_parameters']
          value:  './../paper_presims/patient_285/final' #'./../3D_presim/output/output00000112' # './../paper_presims/patient_80/final'
      treatment_time_step:
          parent_nodes: ['user_parameters']
          value: 720
      treatment_strength:
          parent_nodes: ['user_parameters']
          value: 6.0e2 # 3.0e2 or 6.0e2

  # LatticeBased environment settings
  GridEnv:
    cell_positioning: 'surround_mutant' # 'surround_mutant' # 'random' # 'load'

# evaluation configuration
eval:
  most_recent: 0
  from_file: 0
  path: './'
  model_prefix: '29022024_mela_2d_newest'
  step_to_load: '_best_reward'
  save_name: '_2d_pc_fixed_1_2_position_test'
  # evaluation settings
  fixed_AT_protocol: 1
  at_type: 'fixed' # 'mtd' # 'fixed' # 'zhang_et_al'# 'no_treatment'
  threshold: 1.2
  num_episodes: 5
  evaluate_on: 'PcEnv' # 'PcEnv' # 'LvEnv' # 'GridEnv'


# Predefined parameters for particular patients
patients:
  1:
    initial_wt: 2766
    initial_mut: 0
    growth_rate_wt: 0.231 # 0.0175
    growth_rate_mut: 0.343 # 0.0175
    death_rate_wt: 0.00231
    death_rate_mut: 0.00343
    treat_death_rate_wt: 0.333 # 0.015
    treat_death_rate_mut: 0.00 # 0.0
    LvEnv:
      carrying_capacity: 6500
      competition_wt: 1.423 #2400.0
      competition_mut: 0.391
    PcEnv:
      filename_chkpt:
        parent_nodes: [ 'user_parameters' ]
        value: './../paper_presims/patient_1/final'
    SLvEnv:
      mutant_distance_to_front: 20
      competition_wt: 1.323 #2400.0
      competition_mut: 0.336

  4:
    initial_wt: 2961
    initial_mut: 1
    growth_rate_wt: 0.285 # 0.0175
    growth_rate_mut: 0.313 # 0.0175
    death_rate_wt: 0.00285
    death_rate_mut: 0.00313
    treat_death_rate_wt: 0.384 # 0.015
    treat_death_rate_mut: 0.00 # 0.0
    LvEnv:
      carrying_capacity: 6500
      competition_wt: 1.694 #2400.0
      competition_mut: 0.485
    PcEnv:
      filename_chkpt:
        parent_nodes: [ 'user_parameters' ]
        value: './../paper_presims/patient_4/final'
    SLvEnv:
      mutant_distance_to_front: 20
      competition_wt: 1.323 #2400.0
      competition_mut: 0.336

  55:
    initial_wt: 2558
    initial_mut: 3
    growth_rate_wt: 0.223 # 0.0175
    growth_rate_mut: 0.431 # 0.0175
    death_rate_wt: 0.00223
    death_rate_mut: 0.00431
    treat_death_rate_wt: 0.237 # 0.015
    treat_death_rate_mut: 0.00 # 0.0
    LvEnv:
      carrying_capacity: 6500
      competition_wt: 0.013 #2400.0
      competition_mut: 0.363
    PcEnv:
      filename_chkpt:
        parent_nodes: [ 'user_parameters' ]
        value: './../paper_presims/patient_55/final'
    SLvEnv:
      mutant_distance_to_front: 20
      competition_wt: 1.323 #2400.0
      competition_mut: 0.336

  80:
    initial_wt: 2761
    initial_mut: 1
    growth_rate_wt: 0.29 # 0.0175
    growth_rate_mut: 0.438 # 0.0175
    death_rate_wt: 0.0029
    death_rate_mut: 0.00438
    treat_death_rate_wt: 0.397 # 0.015
    treat_death_rate_mut: 0.00 # 0.0
    LvEnv:
      carrying_capacity: 6500
      competition_wt: 1.323 #2400.0
      competition_mut: 0.336
    PcEnv:
      filename_chkpt:
        parent_nodes: [ 'user_parameters' ]
        value: './../paper_presims/patient_80/final'
    SLvEnv:
      mutant_distance_to_front: 20
      competition_wt: 1.323 #2400.0
      competition_mut: 0.336

  93:
    initial_wt: 2807
    initial_mut: 1
    growth_rate_wt: 0.255 # 0.0175
    growth_rate_mut: 0.448 # 0.0175
    death_rate_wt: 0.00255
    death_rate_mut: 0.00448
    treat_death_rate_wt: 0.366 # 0.015
    treat_death_rate_mut: 0.00 # 0.0
    LvEnv:
      carrying_capacity: 6500
      competition_wt: 2.265 #2400.0
      competition_mut: 0.135
    PcEnv:
      filename_chkpt:
        parent_nodes: [ 'user_parameters' ]
        value: './../paper_presims/patient_93/final'
    SLvEnv:
      mutant_distance_to_front: 20
      competition_wt: 1.323 #2400.0
      competition_mut: 0.336

  111:
    initial_wt: 2761
    initial_mut: 1
    growth_rate_wt: 0.29 # 0.0175
    growth_rate_mut: 0.438 # 0.0175
    death_rate_wt: 0.0029
    death_rate_mut: 0.00438
    treat_death_rate_wt: 0.397 # 0.015
    treat_death_rate_mut: 0.00 # 0.0
    LvEnv:
      carrying_capacity: 6500
      competition_wt: 1.323 #2400.0
      competition_mut: 0.336
    PcEnv:
      filename_chkpt:
        parent_nodes: [ 'user_parameters' ]
        value: './../paper_presims/patient_80/final'
    SLvEnv:
      mutant_distance_to_front: 20
      competition_wt: 1.323 #2400.0
      competition_mut: 0.336

  112:
    initial_wt: 2761
    initial_mut: 1
    growth_rate_wt: 0.29 # 0.0175
    growth_rate_mut: 0.438 # 0.0175
    death_rate_wt: 0.0029
    death_rate_mut: 0.00438
    treat_death_rate_wt: 0.397 # 0.015
    treat_death_rate_mut: 0.00 # 0.0
    LvEnv:
      carrying_capacity: 6500
      competition_wt: 1.323 #2400.0
      competition_mut: 0.336
    PcEnv:
      filename_chkpt:
        parent_nodes: [ 'user_parameters' ]
        value: './../paper_presims/patient_80/final'
    SLvEnv:
      mutant_distance_to_front: 25
      competition_wt: 1.323 #2400.0
      competition_mut: 0.336

  113:
    initial_wt: 2761
    initial_mut: 1
    growth_rate_wt: 0.29 # 0.0175
    growth_rate_mut: 0.438 # 0.0175
    death_rate_wt: 0.0029
    death_rate_mut: 0.00438
    treat_death_rate_wt: 0.397 # 0.015
    treat_death_rate_mut: 0.00 # 0.0
    LvEnv:
      carrying_capacity: 6500
      competition_wt: 1.323 #2400.0
      competition_mut: 0.336
    PcEnv:
      filename_chkpt:
        parent_nodes: [ 'user_parameters' ]
        value: './../paper_presims/patient_80/final'
    SLvEnv:
      mutant_distance_to_front: 30
      competition_wt: 1.323 #2400.0
      competition_mut: 0.336
