# global configuration
global:
  machine: 'mela' # 'mela' # 'raven'
  transport_type: 'ipc://' # Linux: 'ipc://' # Windows: 'tcp://'
  transport_address: '/tmp/' # for raven use '/ptmp/saif/', for mela use '/tmp/'. For windows use '5555'
  evaluate_after: 0

# job configuration
job:
  nodes: 1
  ntasks: 1
  mem-per-task: 300
  cpus-per-task: 20
  time: '24:00:00'
  agent_buffer: 1

# Reinforcement learning configuration
learning:
  # Model options 
  model:
    name: 'PPO' #'RecurrentPPO' 'PPO' 'QRDQN' 'DQN' 'A2C' 'ACKTR' 'ACER' 'DDPG' 'PPO2' 'SAC' 'TRPO'
    policy: 'CnnPolicy' #'MlpLstmPolicy' # 'MlpPolicy'# 'CnnPolicy'
    model_kwargs:
      n_steps: 1024
      verbose: 1
      ent_coef: 0.001
      clip_range: 0.05
      learning_rate: 3.e-5
    total_timesteps: 1.e+9
    save_freq: 'best' # 1.e+6 use string for best reward save, int for every n steps
    model_save_prefix: '0502_load_cnn_ppo'
    load:
      enable_loading: 1 
      last_model: 0
      saved_model_name: './Training/SavedModels/0501_load_cnn_ppo_best_reward'
  network:
    n_lstm_layers: 2
    lstm_hidden_size: 64

# Environment configuration
env:
  # general env settings
  type: 'GridEnv' # 'PcEnv' # 'LvEnv' # 'GridEnv'
  n_envs: 1
  wrap: 1
  wrapper: 'VecFrameStack' # 'DummyVecEnv' # 'VecFrameStack' # 'SubprocVecEnv'
  wrapper_kwargs: #
    n_stack: 4
    channels_order: 'first'
  reward_shaping: 0  # reward shaping flag for some predefined rewards

  # general simulation settings
  max_tumor_size: 2000
  treatment_time_step: 1 
  max_time: 1000
  normalize: 0
  normalize_to: 2000
  observation_type: 'image' # 'image' # 'number'
  action_type: 'discrete' # 'discrete' # 'continuous'
  image_size: 84

  # LV environment settings
  LV:
    initial_wt: 249
    initial_mut: 10
    carrying_capacity: 7500
    growth_rate_wt: 0.0357 #0.0175
    growth_rate_mut: 0.0275 #0.0175
    death_rate_wt: 0.0036
    death_rate_mut: 0.0036
    treat_death_rate_wt: 0.02 #0.015
    treat_death_rate_mut: 0.00 #0.0
    competition_wt: 2.5 #2400.0
    competition_mut: 1.0
    growth_function_flag: 2 # flag for growth function 0 - for delayed death, 1 - for immediate

  # note this is not yet functional
  PC:
    use_2D:
        parent_nodes: ['domain']
        value: 'true'
    number_of_susceptible_cells:
        parent_nodes: ['user_parameters']
        value: 99
    number_of_resistant_cells:
        parent_nodes: ['user_parameters']
        value: 1
    enable_chkpt:
        parent_nodes: ['user_parameters']
        value: 'true'
    filename_chkpt:
        parent_nodes: ['user_parameters']
        value: './../presims/long_train_test_patient/final'
    treatment_time_step:
        parent_nodes: ['user_parameters']
        value: 60
    treatment_death_rate:
        parent_nodes: ['user_parameters']
        value: 0.00225

  # LatticeBased environment settings
  GridEnv:
    initial_wt: 1
    initial_mut: 1
    wt_growth_rate: 0.25
    mut_growth_rate: 0.09
    wt_death_rate: 0.01
    mut_death_rate: 0.01
    wt_treat_death_rate: 0.22
    mut_treat_death_rate: 0.00
    cell_positioning: 'load' # 'surround_mutant' # 'random' # 'load'


# evaluation configuration
eval:
  most_recent: 0
  from_file: 1
  path: './'
  model_prefix: '0502_load_cnn_ppo'
  fixed_AT_protocol: 0
  at_type: 'no_treatment' # 'mtd' # 'fixed' # 'zhang_et_al'# 'no_treatment'
  num_episodes: 10
  step_to_load: '_best_reward'
  save_name: '0428_best'
  evaluate_on: 'GridEnv' # 'PcEnv' # 'LvEnv' # 'GridEnv'

