# global configuration
global:
  transport_type: 'ipc://'
  transport_address: '/tmp/' # for raven use '/ptmp/saif/'
  evaluate_after: 0

# job configuration
job:
  nodes: 1
  ntasks: 1
  mem-per-task: 300
  cpus-per-task: 6
  time: '15:00:00'
  agent_buffer: 1

# Reinforcement learning configuration
learning:
  # Model options 
  model:
    name: 'RecurrentPPO'
    n_envs: 1
    n_steps: 2056
    verbose: 1
    ent_coef: 0.01
    total_timesteps: 1.e+6
    save_freq: 2.e+5
    model_save_prefix: 'rPPO_LSTM_no_resistant_try_to_kill'
    load:
      enable_loading: 0
      external_file_loading: 0
      external_file_name: './data/LV_not_treat_pretrained'
# Environment configuration
env:
  # general env settings
  type: 'LV' #'PhysiCell' # 'LV'
  threshold_burden: 1000
  treatment_time_step: 60
  max_time: 60000
  reward_shaping: 5   # reward shaping flag for some predefined rewards
  normalize_to: 1000

  # LV environment settings
  LV:
    initial_wt: 800
    initial_mut: 0
    carrying_capacity: 1500.0
    growth_rate_wt: 0.035 #0.0175
    growth_rate_mut: 0.022 #0.0175
    death_rate_wt: 0.00036
    death_rate_mut: 0.00036
    treat_death_rate_wt: 0.2 #0.015
    treat_death_rate_mut: 0.00 #0.0
    competition_wt: 1.15 #2400.0
    competition_mut: 1.0
    growth_function_flag: 1 # flag for growth function 0 - for delayed death, 1 - for immediate


  # note this is not yet functional
  PC:
    use_2D:
        parent_nodes: ['domain']
        value: 'true'
    number_of_susceptible_cells:
        parent_nodes: ['user_parameters']
        value: 95
    number_of_resistant_cells:
        parent_nodes: ['user_parameters']
        value: 5
    enable_chkpt:
        parent_nodes: ['user_parameters']
        value: 'true'
    filename_chkpt:
        parent_nodes: ['user_parameters']
        value: './../presims/patient_1/final'

# evaluation configuration
eval:
  most_recent: 0
  from_file: 1
  path: './'
  model_prefix: 'rPPO_LSTM_with_fixed_random_ini2'
  fixed_AT_protocol: 0
  num_episodes: 10
  step_to_load: '_500000_steps'
  evaluate_on: 'LV'


