# global configuration
global:
  transport_type: 'ipc://' # Linux: 'ipc://' # Windows: 'tcp://'
  transport_address: '/tmp/' # for raven use '/ptmp/saif/', for mela use '/tmp/'. For windows use '5555'
  evaluate_after: 0

# job configuration
job:
  nodes: 1
  ntasks: 1
  mem-per-task: 300
  cpus-per-task: 6
  time: '10:00:00'
  agent_buffer: 1

# Reinforcement learning configuration
learning:
  # Model options 
  model:
    name: 'PPO' #'RecurrentPPO' 'PPO' 'QRDQN' 'DQN' 'A2C' 'ACKTR' 'ACER' 'DDPG' 'PPO2' 'SAC' 'TRPO'
    policy: 'CnnPolicy' #'MlpLstmPolicy' # 'MlpPolicy'# 'CnnPolicy'
    model_kwargs:
      n_steps: 512
      verbose: 1
      ent_coef: 0.01
      clip_range: 0.02
      learning_rate: 2.5e-4
    total_timesteps: 1.e+4
    save_freq: 1.e+6
    model_save_prefix: '0425_pcenv'
    load:
      enable_loading: 0
      last_model: 0
      saved_model_name: './Training/SavedModels/12_PPO_LV_tra_dont_treat_3_load_survive_2200000_steps'
  network:
    n_lstm_layers: 2
    lstm_hidden_size: 64

# Environment configuration
env:
  # general env settings
  type: 'PcEnv' # 'PcEnv' # 'LVEnv' # 'GridEnv'
  n_envs: 8
  wrap: 1
  wrapper: 'SubprocVecEnv' # 'DummyVecEnv' # 'VecFrameStack' # 'SubprocVecEnv'
  wrapper_kwargs: #
    n_stack: 4
    channels_order: 'first'
  reward_shaping: 0  # reward shaping flag for some predefined rewards

  # general simulation settings
  threshold_burden: 1000
  treatment_time_step: 1 
  max_time: 1000
  normalize: 1
  normalize_to: 1000

  # LV environment settings
  LV:
    initial_wt: 2490
    initial_mut: 10
    carrying_capacity: 7500
    growth_rate_wt: 0.0357 #0.0175
    growth_rate_mut: 0.0275 #0.0175
    death_rate_wt: 0.0036
    death_rate_mut: 0.0036
    treat_death_rate_wt: 0.02 #0.015
    treat_death_rate_mut: 0.00 #0.0
    competition_wt: 2.5 #2400.0
    competition_mut: 1.0
    growth_function_flag: 2 # flag for growth function 0 - for delayed death, 1 - for immediate

  # note this is not yet functional
  PC:
    use_2D:
        parent_nodes: ['domain']
        value: 'true'
    number_of_susceptible_cells:
        parent_nodes: ['user_parameters']
        value: 99
    number_of_resistant_cells:
        parent_nodes: ['user_parameters']
        value: 1
    enable_chkpt:
        parent_nodes: ['user_parameters']
        value: 'false'
    filename_chkpt:
        parent_nodes: ['user_parameters']
        value: './../presims/test_patient/output00000003'
    treatment_time_step:
        parent_nodes: ['user_parameters']
        value: 60
    treatment_death_rate:
        parent_nodes: ['user_parameters']
        value: 0.00225

  # LatticeBased environment settings
  GridEnv:
    grid_size: 36
    observation_type: 'image'
    action_type: 'discrete'
    initial_wt: 1
    initial_mut: 1
    wt_growth_rate: 0.1
    mut_growth_rate: 0.02
    wt_death_rate: 0.002
    mut_death_rate: 0.002
    wt_treat_death_rate: 0.02
    mut_treat_death_rate: 0.00
    cell_positioning: 'surround_mutant' # 'surround_mutant' # 'random'


# evaluation configuration
eval:
  most_recent: 0
  from_file: 0
  path: './'
  model_prefix: '0418_stacked_image_PC_test'
  fixed_AT_protocol: 1
  at_type: 'mtd' # 'mtd' # 'fixed' # 'zhang_et_al'
  num_episodes: 1
  step_to_load: '_300000_steps'
  save_name: '0424mtd_test'
  evaluate_on: 'PcEnv' # 'PcEnv' # 'LvEnv' # 'GridEnv'

