# global configuration
global:
  transport_type: 'ipc://'
  transport_address: '/tmp/' # for raven use '/ptmp/saif/'
  evaluate_after: 0

# job configuration
job:
  nodes: 1
  ntasks: 1
  mem-per-task: 3000
  cpus-per-task: 1
  time: '05:00:00'
  agent_buffer: 1

# PhysiCell configuration
PhysiCell:
  cells: None

# Reinforcement learning configuration
learning:
  # Model options 
  model:
    name: 'PPO'
    n_envs: 1
    n_steps: 300
    verbose: 1
    ent_coef: 0.01
    total_timesteps: 1.e+7
    save_freq: 100000
    model_save_prefix: '020223PPO_no_treat_test'
    load:
      enable_loading: 1
      external_file_loading: 0
      external_file_name: './data/LV_not_treat_pretrained'
  # Environment configuration  
  env:
    type: 'LV' #'PhysiCell' # 'LV'
    burden: 1000
    treatment_time_step: 60
    max_time: 60000
    initial_wt: 45
    initial_mut: 5
    # reward shaping flag for some predefined rewards
    reward_shaping: 4
      
