# global configuration
global:
  transport_type: 'ipc://'
  transport_address: '/tmp/' # for raven use '/ptmp/saif/'
  evaluate_after: 0

# job configuration
job:
  nodes: 1
  ntasks: 1
  mem-per-task: 300
  cpus-per-task: 4
  time: '15:00:00'
  agent_buffer: 1

# Reinforcement learning configuration
learning:
  # Model options 
  model:
    name: 'PPO' #'RecurrentPPO' # 'PPO'
    policy: 'CnnPolicy' #'MlpLstmPolicy' # 'MlpPolicy'# 'CnnPolicy'
    model_kwargs:
      n_steps: 1024
      verbose: 1
      ent_coef: 0.005
      clip_range: 0.02
      learning_rate: 5.e-4
    total_timesteps: 1.e+6
    save_freq: 1.e+5
    model_save_prefix: 'LatticeBased_24_03_CNN_1_env_4_stacked_mela'
    load:
      enable_loading: 0
      last_model: 0
      saved_model_name: './Training/SavedModels/12_PPO_LV_tra_dont_treat_3_load_survive_2200000_steps'
  network:
    n_lstm_layers: 2
    lstm_hidden_size: 64

# Environment configuration
env:
  # general env settings
  type: 'LatticeBased' #'PhysiCell' # 'LV' # 'LatticeBased'
  n_envs: 1
  wrap: 1
  wrapper: 'VecFrameStack' # 'DummyVecEnv' # 'VecFrameStack'
  wrapper_kwargs: #
    n_stack: 4
    channels_order: 'first'
  reward_shaping: 7  # reward shaping flag for some predefined rewards

  # general simulation settings
  threshold_burden: 5000
  treatment_time_step: 1 
  max_time: 1000
  normalize_to: 1000

  # LV environment settings
  LV:
    initial_wt: 2490
    initial_mut: 10
    carrying_capacity: 7500
    growth_rate_wt: 0.0357 #0.0175
    growth_rate_mut: 0.0275 #0.0175
    death_rate_wt: 0.0036
    death_rate_mut: 0.0036
    treat_death_rate_wt: 0.02 #0.015
    treat_death_rate_mut: 0.00 #0.0
    competition_wt: 2.5 #2400.0
    competition_mut: 1.0
    growth_function_flag: 2 # flag for growth function 0 - for delayed death, 1 - for immediate

  # note this is not yet functional
  PC:
    use_2D:
        parent_nodes: ['domain']
        value: 'true'
    number_of_susceptible_cells:
        parent_nodes: ['user_parameters']
        value: 5997
    number_of_resistant_cells:
        parent_nodes: ['user_parameters']
        value: 3
    enable_chkpt:
        parent_nodes: ['user_parameters']
        value: 'true'
    filename_chkpt:
        parent_nodes: ['user_parameters']
        value: './../presims/test_patient/output00000003'
    treatment_time_step:
        parent_nodes: ['user_parameters']
        value: 240
    treatment_death_rate:
        parent_nodes: ['user_parameters']
        value: 0.00225

  # LatticeBased environment settings
  LB:
    lattice_size: 100
    lattice_type: 'square' # 'square' # 'hexagonal'
    lattice_shape: 'square' # 'square' # 'hexagonal'
    lattice_shape_kwargs:
      radius: 1
    lattice_kwargs:
# evaluation configuration
eval:
  most_recent: 0
  from_file: 1 
  path: './'
  model_prefix: 'LatticeBased_23_03_CNN_1_env_not_stacked'
  fixed_AT_protocol: 0
  num_episodes: 1
  step_to_load: '_500000_steps'
  save_name: '12_policy_LV_before_training_check'
  evaluate_on: 'LatticeBased' #'PhysiCell' # 'LV' # 'LatticeBased'

