# global configuration
global:
  transport_type: 'ipc://'
  transport_address: '/tmp/' # for raven use '/ptmp/saif/'
  evaluate_after: 0

# job configuration
job:
  nodes: 1
  ntasks: 1
  mem-per-task: 3000
  cpus-per-task: 2
  time: '15:00:00'
  agent_buffer: 1

# Reinforcement learning configuration
learning:
  # Model options 
  model:
    name: 'PPO'
    n_envs: 1
    n_steps: 1000
    verbose: 1
    ent_coef: 0.01
    total_timesteps: 1.e+8
    save_freq: 1.e+7
    model_save_prefix: '22_02_23_rew_f=4_actual_params_instant_treat'
    load:
      enable_loading: 0
      external_file_loading: 0
      external_file_name: './data/LV_not_treat_pretrained'
# Environment configuration
env:
  # general env settings
  type: 'LV' #'PhysiCell' # 'LV'
  threshold_burden: 1000
  treatment_time_step: 60
  max_time: 60000
  reward_shaping: 0   # reward shaping flag for some predefined rewards

  # LV environment settings
  LV:
    initial_wt: 45
    initial_mut: 5
    carrying_capacity: 1500.0
    growth_rate_wt: 0.035 #0.0175
    growth_rate_mut: 0.032 #0.0175
    death_rate_wt: 0.00036
    death_rate_mut: 0.00036
    treat_death_rate_wt: 0.15 #0.015
    treat_death_rate_mut: 0.00 #0.0
    competition_wt: 1.0 #2400.0
    competition_mut: 1.0
    growth_function_flag: 4 # flag for growth function 0 - for delayed death, 1 - for immediate


  # note this is not yet functional
  PC:
    use_2D:
        parent_nodes: ['domain']
        value: 'false'
    number_of_susceptible_cells:
        parent_nodes: ['user_parameters']
        value: 42
    number_of_resistant_cells:
        parent_nodes: ['user_parameters']
        value: 51

# evaluation configuration
eval:
  most_recent: 0
  from_file: 1
  path: './'
  model_prefix: '22_02_23_rew_f=0_actual_params_instant_treat'
  fixed_AT_protocol: 0
  num_episodes: 1
  step_to_load: '_70000000_steps'
  evaluate_on: 'PhysiCell'


